apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-server-deployment
  labels:
    app: async-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-server
  template:
    metadata:
      labels:
        app: async-server
    spec:
      containers:
        - name: server
          image: learncloudnative/async-server:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: QUEUE_URL
              value: "amqp://admin:admin@my-rabbit-rabbitmq-ha.rabbit.svc.cluster.local"
