apiVersion: apps/v1
kind: Deployment
metadata:
  name: sha
spec:
  selector:
    matchLabels:
      app: sha
  template:
    metadata:
      labels:
        app: sha
    spec:
      containers:
        - name: sha
          image: sha
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sha
spec:
  selector:
    app: sha
  ports:
    - port: 8080
  type: LoadBalancer
