apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  labels:
    name: prom-config
data:
  prometheus.yml: |-
    global: 
      scrape_interval: 5s 
    scrape_configs: 
      - job_name: prometheus
        static_configs: 
        - targets: ['square']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          imagePullPolicy: Always
          name: prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prom-config-volume
              mountPath: /etc/prometheus
            - name: prom-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prom-config-volume
          configMap:
            defaultMode: 420
            name: prom-config
        - name: prom-storage-volume
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      name: http
      targetPort: 9090
